# Generated by Django 5.1.5 on 2025-02-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='color',
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ManyToManyField(to='main.color'),
        ),
    ]
