# Generated by Django 5.1.5 on 2025-02-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_car_color_car_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='shop',
            field=models.ManyToManyField(to='main.shop'),
        ),
    ]
